.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. smartusd_qt test_smartusd_qt
clean: FORCE
	$(MAKE) -C .. smartusd_qt_clean test_smartusd_qt_clean
check: FORCE
	$(MAKE) -C .. test_smartusd_qt_check
smartusd-qt smartusd-qt.exe: FORCE
	 $(MAKE) -C .. smartusd_qt
