.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. powerblockcoin_qt test_powerblockcoin_qt
clean: FORCE
	$(MAKE) -C .. powerblockcoin_qt_clean test_powerblockcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_powerblockcoin_qt_check
powerblockcoin-qt powerblockcoin-qt.exe: FORCE
	 $(MAKE) -C .. powerblockcoin_qt
